# Appveyor configuration template for Rust using rustup for Rust installation
# https://github.com/starkat99/appveyor-rust

os: Visual Studio 2015

environment:
  matrix:
  # Nightly 64-bit MSVC
    - channel: nightly
      PYTHON: "C:\\Python37"
      target: x86_64-pc-windows-msvc

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin

  - "%PYTHON%/Scripts/pip.exe install nose"

  - if %channel% == "nightly" rustup install nightly

  - if %channel% == "nightly" rustup component add rustfmt --toolchain nightly
  - if %channel% == "stable" rustup component add clippy
  - if %channel% == "nightly" rustup component add clippy --toolchain nightly

  - rustc -vV
  - cargo -vV

# cargo does this for us
build: false
test_script:
  - if %channel% == "nightly" cargo +nightly fmt --all -- --check
  - if %channel% == "stable" cargo clippy -- -D warnings
  - if %channel% == "nightly" cargo +nightly clippy -- -D warnings

  - cargo test --verbose
