language: rust
# cache dependencies
cache: cargo
rust:
  - stable
  - nightly

dist: xenial
python:
  - "3.7"

sudo: true
before_install:
  - sudo apt-get update

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

branches:
  only:
    - master

before_script:
  # Python
  - sudo apt-get install python3

  # Cargo components
  - if [ $TRAVIS_RUST_VERSION == nightly ]; then rustup component add rustfmt --toolchain nightly; fi
  - if [ $TRAVIS_RUST_VERSION == stable ]; then rustup component add clippy; fi

before_install:
  # grcov
  - curl -L https://github.com/mozilla/grcov/releases/download/v0.4.1/grcov-linux-x86_64.tar.bz2 | tar jxf -

after_success:
  # Coverage report
  - if [ $TRAVIS_RUST_VERSION == nightly ]; then bash <(curl -s https://codecov.io/bash) -f lcov.info; fi

script:
  # fail when formatting error encountered
  - if [ $TRAVIS_RUST_VERSION == nightly ]; then cargo +nightly fmt --all -- --check; fi
  # fail when encountering clippy warnings
  - if [ $TRAVIS_RUST_VERSION == stable ]; then cargo clippy -- -D warnings; fi

  - export CARGO_INCREMENTAL=0
  - |
    if [ $TRAVIS_RUST_VERSION == nightly ]; then
      export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads";
    fi
  - cargo build --verbose
  - cargo test --verbose

  # Coverage report
  - |
    if [ $TRAVIS_RUST_VERSION == nightly ]; then
      zip -0 ccov.zip `find . \( -name "mamba*.gc*" \) -print`;
      ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore-dir "/*" -o lcov.info;
    fi
