os:
  - osx
  - linux

language: rust
rust:
  - stable
  - nightly

dist: xenial
python:
  - "3.7"

# cache dependencies
before_cache:
  - if [ $TRAVIS_OS_NAME = 'osx' ]; then brew cleanup; fi
cache:
  directories:
    - if [ $TRAVIS_OS_NAME = 'osx' ]; then $HOME/Library/Caches/Homebrew; fi
  - cargo

sudo: true
before_install:
  - sudo apt-get update

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

branches:
  only:
    - master

before_script:
  # Python
  - if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install python3; fi
  - if [ $TRAVIS_OS_NAME = 'osx' ]; then brew install python3; fi

  # Cargo components
  - if [ $TRAVIS_RUST_VERSION = 'nightly' AND $TRAVIS_OS_NAME = 'linux' ]; then rustup component add rustfmt --toolchain nightly; fi
  - if [ $TRAVIS_RUST_VERSION = 'stable' AND $TRAVIS_OS_NAME = 'linux' ]; then rustup component add clippy; fi

before_install:
  # grcov
  - curl -L https://github.com/mozilla/grcov/releases/download/v0.4.1/grcov-linux-x86_64.tar.bz2 | tar jxf -

after_success:
  # Coverage report
  - if [ $TRAVIS_RUST_VERSION = 'nightly' AND $TRAVIS_OS_NAME = 'linux' ]; then bash <(curl -s https://codecov.io/bash); fi

script:
  - if [ $TRAVIS_RUST_VERSION = 'stable' AND $TRAVIS_OS_NAME = 'linux' ]; then cargo clippy -- -D warnings; fi
  - if [ $TRAVIS_RUST_VERSION = 'nightly' AND $TRAVIS_OS_NAME = 'linux' ]; then cargo +nightly fmt --all -- --check; fi

  - cargo build
  - cargo test

  - |
    if [ $TRAVIS_RUST_VERSION = 'nightly' AND $TRAVIS_OS_NAME = 'linux' ]; then
      export CARGO_INCREMENTAL=0;
      export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads";
      zip -0 ccov.zip `find . \( -name "mamba*.gc*" \) -print`;
      ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore-dir "/*" lcov.info;
    fi
