language: rust
dist: xenial
python:
  - "3.7"

sudo: true
before_install:
  - sudo apt-get update

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

branches:
  only:
    - master

before_script:
  # Python
  - sudo apt-get install python3

  # Cargo components
  - rustup install stable
  - rustup install nightly
  - rustup component add rustfmt --toolchain nightly
  - rustup component add clippy

  # grcov
  - curl -L https://github.com/mozilla/grcov/releases/download/v0.4.1/grcov-linux-x86_64.tar.bz2 | tar jxf -

after_success:
  # Coverage report
  - bash <(curl -s https://codecov.io/bash)

script:
  # fail when formatting error encountered
  - cargo +nightly fmt --all -- --check
  # fail when encountering clippy warnings
  - cargo clippy -- -D warnings

  - cargo build --verbose
  - cargo test --verbose

  # Coverage report
  - |
    zip -0 ccov.zip `find . \( -name "mamba*.gc*" \) -print`;
    ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore-dir "/*" -o lcov.info;
    bash <(curl -s https://codecov.io/bash) -f lcov.info;
