[package]
name = "mamba"
version = "0.1.0"
authors = ["Joel Abrahams <abrahamsjo@gmail.com>"]
edition = "2018"

[dependencies]
assert_cmd = "0.10"
python-parser = "0.1.0"
clap = {version = "2.33", features = ["yaml"]}
leg = "0.1.3"
pathdiff = "0.1.0"
glob = "0.3.0"
