name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python: ["3.8"]
        rust: ["+nightly"]

    runs-on: ${{ matrix.os }}

    name: Test on OS ${{ matrix.os }} using Python v${{ matrix.python }}, Rust ${{ matrix.rust }}

    steps:
    - uses: actions/checkout@v2

    # Install Python
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    # Install Rust, build and run tests
    - name: Install Rust ${{ matrix.rust }}
      run: rustup toolchain install ${{ matrix.rust }}
    - name: Build
      run: cargo +nightly build --verbose
    - name: Run tests
      run: cargo +nightly test --package mamba --verbose
